remove Xamarin support
dimonovdd/Xamarin.MediaGallery pull request #129
Opened 2024-10-25 21:40 UTC by dimonovdd

### Related to issue

#128 
#124 

### API Changes

remove Xamarin support

### Recommendations for testing

### PR Checklist ###

- [X] All projects build
- [X] Has samples
- [X] Rebased onto current `main`

2024-10-25 21:43 UTC, dimonovdd commented
@beeradmoore Hi

Sorry, Maybe, do you have a desire to do a review? I also plan to make a separate pull request to improve the sample project.

2024-10-26 02:29 UTC, beeradmoore commented
Yep. I'll give this a look at this weekend 👍

2024-10-26 23:58 UTC, beeradmoore commented on Sample/.DS_Store
`.DS_Store` should be added to the `.gitignore`

2024-10-27 00:57 UTC, beeradmoore requested changes
Looks good. I was able to build the sample for iOS simulator. When I can I'll also build for iOS device and Android device and see how it performs. 

I was not able to build the nuget package however.

2024-10-27 00:57 UTC, beeradmoore commented on MediaGallery/MediaGallery.csproj
How do you feel about adding `<Nullable>enable</Nullable>`, likely in a post release update?
I like it in my projects so I can ensure I am checking for null where necessary. Unsure if it works the same in libraries.

2024-10-27 00:57 UTC, beeradmoore commented on Sample/Resources/Fonts/OpenSans-Semibold.ttf
I believe these fonts can be deleted (same with the dotnet_bot.png) as they are not being used in the `MauiProgram.cs`

2024-10-27 00:57 UTC, beeradmoore commented on Sample/Sample.Maui.csproj
IMO the `Microsoft.Maui.Controls` and `Microsoft.Maui.Controls.Compatibility` nuget versions should be set explicitly. Latest stable as of today is `[8.0.92](https://www.nuget.org/packages/Microsoft.Maui.Controls.Compatibility/8.0.92)`.

I think using what there is now means it will use whatever MAUI is installed on the system, and that can be different for different people.

2024-10-27 00:57 UTC, beeradmoore commented on Sample/Sample.csproj
This csproj is not referenced in the sln. Was this added by mistake?

2024-10-27 00:57 UTC, beeradmoore commented on Sample/Views/MediaFileInfoPage.xaml.cs
Not huge because it is just the sample app, but this can be tidied up with `#if __ANDROID__`, that way events are not even subscribed to on iOS

2024-10-27 00:57 UTC, beeradmoore commented on Sample/Views/PickPage.xaml
I haven't had to bind with `xmlns:xaml` before. Have I been missing out on something extra, or does it just do that by default?

2024-10-27 00:57 UTC, beeradmoore commented on MediaGallery/MediaGallery.csproj
I like how much all of this got tidied up. 

`LangVersion` is still set to 10. Default in .NET 8 is 12, so should we bump this to 12 as well?

2024-10-27 00:57 UTC, beeradmoore commented on MediaGallery/ExceptionHelper/ExceptionHelper.shared.cs
For the checks that go

```csharp
#if __ANDROID__
    // Android stuff here
 #else
    // iOS stuff here
 #endif
```

Would it make more sense to do something like

```csharp
#if __ANDROID__
    // Android stuff here
 #elif __IOS__
    // iOS stuff here
 #else
     // I don't know, maybe throw an exception, maybe add something that will cause compiler issue?
 #endif
```

So that way its more explicit what is in the else? Would also help in the future if support is added for Windows and Mac Catalyst.

2024-10-27 00:57 UTC, beeradmoore commented on Sample/.DS_Store
`.DS_Store` should be added to the `.gitignore`

2024-10-27 00:57 UTC, beeradmoore commented on MediaGallery/MediaGallery.csproj
`PackageTags` should be updated

2024-10-27 00:57 UTC, beeradmoore commented on MediaGallery/MediaGallery.csproj
I think `<UseMaui>true</UseMaui>` (and maybe `<SingleProject>true</SingleProject>`, though I am not 100% sure what it is doing) should be removed because of the warnings,

>  warning MA002: Starting with .NET 8, setting  <UseMaui>true</UseMaui>  does not automatically include NuGet package references in your project.  Update your project by including this item:  <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.82" />.  You can skip this warning by setting  <SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>  in your project file. 

And that 
```xml
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.92" />
```
should be added. Although you wouldn't want to set its version as latest as it would be the minimum required. Seeing as people have their own version of MAUI installed it should be at least set to `8.0.3` which was the first public release of MAUI for .NET. `Microsoft.Maui.Controls.Compatibility` should not need to be set, I think that is also being removed as of .NET 9.

I am unsure what that does to people who have
```xml
<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
```
set, but also AFAIK they shouldn't be using it like that anymore.

2024-10-27 07:56 UTC, dimonovdd commented on MediaGallery/MediaGallery.csproj
Let it be so, they are for the search

2024-10-27 07:57 UTC, dimonovdd commented on MediaGallery/MediaGallery.csproj
I think it should be done in a separate PR

2024-10-27 07:59 UTC, dimonovdd commented on Sample/Sample.csproj
Yes, it's temporary, I'll fix it in another PR

2024-10-27 08:00 UTC, dimonovdd commented on Sample/Views/MediaFileInfoPage.xaml.cs
Yes, the sample will be edited later

2024-10-27 08:02 UTC, dimonovdd commented on Sample/Views/PickPage.xaml
fix

2024-10-27 08:02 UTC, dimonovdd commented on MediaGallery/MediaGallery.csproj
fixed

2024-10-27 08:09 UTC, dimonovdd commented on Sample/Resources/Fonts/OpenSans-Semibold.ttf
fix

2024-10-27 08:10 UTC, dimonovdd commented on Sample/.DS_Store
fix

2024-10-27 08:27 UTC, dimonovdd commented on MediaGallery/MediaGallery.csproj
maybe you can do it in a separate PR?

2024-10-27 08:30 UTC, dimonovdd commented
@beeradmoore This pull request came out too big and confusing, I'm trying to shorten it.

2024-10-27 08:34 UTC, beeradmoore commented
I don't see it as that. Most of the changes are deleting the old sample and adding the new.

2024-10-27 08:35 UTC, beeradmoore commented on MediaGallery/MediaGallery.csproj
Works for me

2024-10-27 08:36 UTC, beeradmoore commented on MediaGallery/MediaGallery.csproj
Happy to do it as new PR after thsi one is in

2024-10-27 08:58 UTC, dimonovdd commented
> Most of the changes are deleting the old sample and adding the new.

It seems that I have corrected all this. But I don't want to deal with the MAUI versions here. Individual small PRswill be more visual and understandable

2024-10-27 09:23 UTC, dimonovdd commented on MediaGallery/ExceptionHelper/ExceptionHelper.shared.cs
I'm not sure I like it. But this has a big plus, we will get a compilation error if we add another platform and fix it right away.

2024-10-27 09:24 UTC, dimonovdd commented on Sample/Sample.Maui.csproj
I will also fix it in the new one

2024-10-27 10:46 UTC, dimonovdd commented
@beeradmoore tell me what fixes do you consider really critical? I have already prepared two new branches and am ready to create a Pull Requests.  But first we need to merge this Pull Request

2024-10-27 20:46 UTC, beeradmoore commented
I don't see anything else here as critical for a preview release. MAUI versions stuff I'd like to experiment with for a full release. 

Once its in I'd like to look into getting it to build nugets with `dotnet pack` as an ease of convieneince for pumping out local nuget packages to experiment with the MAUI version stuff.

Good job updating it all!

2024-10-29 10:39 UTC, dimonovdd commented
@beeradmoore thx, I deleted .DS_Store files. Would you approve this Pull Request?

2024-10-29 10:46 UTC, beeradmoore commented
@dimonovdd , I don't see an option to approve, just squash and merge.

Unless you mean verbally, in which case looks good

2024-10-29 15:09 UTC, merged