MAUI Version
dimonovdd/Xamarin.MediaGallery pull request #132
Opened 2024-10-31 06:31 UTC by dimonovdd

### Description

### PR Checklist ###

- [X] All projects build
- [X] Has samples
- [X] Rebased onto current `main`

2024-11-02 02:01 UTC, beeradmoore requested changes

2024-11-02 03:07 UTC, dimonovdd commented on Sample/Sample.csproj
But global.json is applied to the full solution

2024-11-02 07:32 UTC, beeradmoore commented on Sample/Sample.csproj
Sorry for the confusion.

8.0.3 in MediaGallery csproj is the minimum allowed MAUI version that is required for the nuget to install into projects.

8.0.3 in globals is the min .NET SDK version required to compile it. Just happened to be the same number 😅

8.0.92 is what the sample project is using is what MAUI is used in that app when it is built. Ideally this is the same as what end users are using.

If you keep MediaGallery as 8.0.92, but my own app is stuck at 8.0.60 due to some unresolved bug that the MAUI team has not fixed, I won't be able to install the MediaGallery nuget as the nuget will have a higher dependency than what the project is using.

2024-11-03 13:59 UTC, dimonovdd commented on Sample/Sample.csproj
But that's one solution. It will take the maximum version of the package for all projects

2024-11-03 14:44 UTC, dimonovdd commented on Sample/Sample.csproj
@beeradmoore  I did it, but I still don't understand the point

2024-11-03 22:14 UTC, beeradmoore commented on Sample/Sample.csproj
When I can pump out a nuget I'll make a more practical example. (Or I will find myself incorrect in the matter 😅)

2024-11-03 22:15 UTC, beeradmoore approved these changes

2024-11-04 04:16 UTC, beeradmoore requested changes

2024-11-04 04:16 UTC, beeradmoore commented on global.json
Trying to load the solution, I get errors because of this file.

I think `8.0.3` here indicates that .NET SDK 8.0.3 is required to build the solution. But .NET 8.0.3 does not exist, .NET 8.0.300 does though.

Personally I use this for `global.json`

```json
{
  "sdk": {
    "version": "8.0.300",
    "rollForward": "latestFeature"
  }
}
```

At minimum someone needs .NET SDK v8.0.300 to build it. Using .NET SDK v8.0.400 will still work because of `latestFeature`. However if .NET SDK v8.1 becomes a thing you'd still be required to have a v8.0.XXX version installed to build it.

Using `latestMinor` instead would allow it to be build with .NET v8.1.XXX SDK, but no idea if that will ever be a thing, or if it would cause any problems. 

Reference: [global.json overview](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json)

2024-11-04 08:47 UTC, dimonovdd commented on global.json
@beeradmoore ok. thx

2024-11-04 09:29 UTC, merged

2024-11-13 03:04 UTC, beeradmoore commented on Sample/Sample.csproj
Hey @dimonovdd , I went and did testing on the MAUI versions and found some things out. I think things changed a little when the get changed from `Microsoft.Maui.Controls` to `Microsoft.Maui.Essentials`.

I have a test repository [here](https://github.com/beeradmoore/MyDependencyTestApp) that has 2 nugets locally in it. `3.0.0-preview` which is as this repository is in its main branch and `3.0.1-preview` which has a slight change.

The build process I did is,

```
rm -rf bin/
rm -rf obj/
dotnet restore
dotnet build --configuration=Release
dotnet pack
```

I then copied the nuget to this project where it is referenced as a local nuget package.

The changes in `3.0.1-preview` is I bumped the nuget package of `Microsoft.Maui.Essentials` to be the latest .NET 8 version, `8.0.93`. For reference `3.0.0-preview` is using `8.0.3`.


If I install `3.0.0-preview` it installs as expected.

![Screenshot 2024-11-13 at 1 36 48 pm](https://github.com/user-attachments/assets/1f545677-6256-4f3a-a4f9-37f142f9cc45)

If I look at the implicitly installed versions it installed `Microsoft.Maui.Essentials` as `8.0.82`. This is expected even though the MediaGallery project is using `8.0.3`, because as a nuget package it means `>= 8.0.3`. When we have `Microsoft.Maui.Controls` `8.0.82` in my app/sample project it has dependency on `Microsoft.Maui.Core` >= `8.0.82`, which then has a dependency of `Microsoft.Maui.Essentials` >= `8.0.82`, which is how that version got installed.

![Screenshot 2024-11-13 at 1 43 40 pm](https://github.com/user-attachments/assets/30df779b-01eb-4500-b56d-95d8a36d3838)

If I update to `3.0.1-preview` which has got `Microsoft.Maui.Essentials` set to `8.0.93`.

It installs correctly as above, the implicitly installed version is `8.0.93` as expected. It is a different version than the other `Microsoft.Maui.*` packages, but that is just how package resolution is allowing it to exist as those other packages need `>= 8.0.82`. There is nothing wrong with it resolving to a newer version. 

![Screenshot 2024-11-13 at 1 47 10 pm](https://github.com/user-attachments/assets/e4a6a13e-a9b7-4ce4-87d5-7daa737bc014)

The problem however is if my project had `Microsoft.Maui.Essentails` explicitly installed. 


Installing `3.0.0-preview`, things are fine. 
![Screenshot 2024-11-13 at 1 49 05 pm](https://github.com/user-attachments/assets/d3e79fe7-41b7-4cbe-a149-40bc0bd4413e)

However if I try upgrade to `3.0.1-preview` it won't install as I have a conflict.

![Screenshot 2024-11-13 at 1 49 33 pm](https://github.com/user-attachments/assets/214e2259-18fb-4dba-ad08-3be2e93f82e9)

My project has - `Microsoft.Maui.Essentials`  == `8.0.82`
The new nuget requires - `Microsoft.Maui.Essentials` >= `8.0.93`

As a consumer of the nuget I can fix the issue by updating `Microsoft.Maui.Essentials` to `8.0.93`. But if there was a bug in there preventing me updating because the bug did not exist in `8.0.82` then that is not an option. 


This problem would have been a lot worse when this repo targeted `Microsoft.Maui.Controls` instead of `Microsoft.Maui.Essentials` as MAUI projects use this out of the box and I don't think people are adding `Microsoft.Maui.Essentials` explicitly.