Fixed the PickAsync method for devices with Android 11
dimonovdd/Xamarin.MediaGallery pull request #61
Opened 2021-09-03 07:05 UTC by andrk0p

### Description
I found that the selection of photos or videos does not work on all devices.

Device:
Xiaomi Redmi Note 8 Pro
MIUI Global 12.5.1
Android 11

The chooserIntent object in all testing cases returns Android.App.Result.Canceled in the onActivityResult method.

I couldn't find a way to get chooserIntent to work correctly on my device, so I added a check for the operating system version to rule out this problem on similar devices.

- Fixed the PickAsync method for devices with Android 11

### API Changes

Added:

```
intent = !Platform.HasSdkVersion(30)
    ? Intent.CreateChooser(intent, request.Title ?? string.Empty)
    : intent;
```

### PR Checklist ###

- [x] All projects build
- [x] Has samples
- [x] Rebased onto current main

2021-09-04 18:00 UTC, dimonovdd commented on MediaGallery/MediaGallery/PickMedia.android.cs
> +                intent = !Platform.HasSdkVersion(30)
Thanks. Сan we add a check based on the device model? I tested this plugin on Android 11 devices and it works correctly.

2021-09-04 20:39 UTC, andrk0p commented on MediaGallery/MediaGallery/PickMedia.android.cs
> +                intent = !Platform.HasSdkVersion(30)
Yes, I can add a device model check using ```Xamarin.Essentials.DeviceInfo.Model```

2021-09-07 20:15 UTC, dimonovdd commented
@andrk0p I was able to test this on a device like yours but with 12.5.2 version of MIUI. I can't reproduce this problem. Do you have any ideas?

2021-09-08 14:26 UTC, andrk0p commented
> 
> 
> @andrk0p I was able to test this on a device like yours but with 12.5.2 version of MIUI. I can't reproduce this problem. Do you have any ideas?

I don't have any ideas. Maybe the problem is in MAUI 12.5.1

2021-09-08 16:28 UTC, dimonovdd commented
@andrk0p Maybe, can we add a new parameter for determining use of `Intent.CreateChooser`?

2021-09-08 18:02 UTC, andrk0p commented
> 
> 
> @andrk0p Maybe, can we add a new parameter for determining use of `Intent.CreateChooser`?

I added the NeedUseCreateChooser parameter and updated the usage example

2021-09-14 19:46 UTC, dimonovdd requested changes
LGTM! I added a few minor edits:

2021-09-14 19:46 UTC, dimonovdd commented on README.md
> +- `UseCreateChooser` specifies whether to use Intent.createChooser for picking.
```suggestion
- `UseCreateChooser` specifies whether to use `Intent.CreateChooser`
```

2021-09-14 19:46 UTC, dimonovdd commented on MediaGallery/MediaGallery/PickMedia.android.cs
> +                    intent = Intent.CreateChooser(intentDisposable, request.Title ?? string.Empty);
```suggestion
                    intent = Intent.CreateChooser(intent, request.Title ?? string.Empty);
```

2021-09-14 19:46 UTC, dimonovdd commented on MediaGallery/MediaGallery/PickMedia.android.cs
> +            Intent intentDisposable = null;
```suggestion
            IDisposable intentDisposable = null;
```

2021-09-14 19:46 UTC, dimonovdd commented on MediaGallery/MediaPickRequest/MediaPickRequest.shared.cs
> +        /// <summary>Gets or sets whether to use Intent.CreateChooser for picking. Currently used only for Android.</summary>
```suggestion
        /// <summary>Gets or sets whether to use Intent.CreateChooser. Currently used only for Android.</summary>
```

2021-09-15 16:48 UTC, dimonovdd approved these changes

2021-09-15 16:56 UTC, merged